export const ADD_DRAWING_LIST = 'ADD_DRAWING_LIST';
export const GENERATE_NAME_LISTS = 'GENERATE_NAME_LISTS';
export const DELETE_DRAWING_LIST = 'DELETE_DRAWING_LIST';
export const DELETE_ALL_DRAWING_LISTS = 'DELETE_ALL_DRAWING_LISTS';
export const NOTIFY_MESSAGE = 'NOTIFY_MESSAGE';